FROM python:3.12-slim AS builder
WORKDIR /app
RUN pip install --no-cache-dir uv
COPY pyproject.toml .
COPY ./app ./app
RUN uv pip install --system --no-cache ".[dev]"

FROM python:3.12-slim
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY pyproject.toml .
COPY ./app ./app
COPY ./tests ./tests
{% if include_alembic -%}
COPY ./alembic ./alembic
COPY ./alembic.ini .
{% endif -%}
COPY ./startup.sh .
RUN chmod +x startup.sh
EXPOSE 8000
CMD ["bash", "startup.sh"]
